stackit: return image status if not 'AVAILABLE'
we are already handling the error from 'GetImage', if the image fails to
be 'AVAILABLE', the error will be 'nil' but we don't return what is the
actual status of the image, hence the current error we see:
```
Error: creating an image: image not available: %!w(<nil>)
```

Signed-off-by: Mathieu Tortuyaux <mtortuyaux@microsoft.com>