kola/k8s/controller: remove healthcheck from kubedns
it appears to be a bit overkill for testing purposes, also it creates
error like:
Error: failed to start container "healthz": Error response from daemon:
OCI runtime create failed: container_linux.go:367: starting container process
caused: process_linux.go:495: container init caused: process_linux.go:458:
setting cgroup config for procHooks process caused: failed to write "20971520":
write /sys/fs/cgroup/memory/kubepods/burstable/pod60a8ff48-\
e6bf-450d-b88d-db171f14147c/healthz/memory.limit_in_bytes: device or
resource busy: unknown